;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-append
	evil-delete-backward-char-and-join
	evil-normal-state
	))

(setq mc/cmds-to-run-once
      '(
	))
