;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-delete-backward-char-and-join
	evil-forward-char
	evil-insert
	evil-normal-state
	evil-substitute
	org-cycle
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	evil-backward-char
	evil-next-visual-line
	evil-previous-visual-line
	))
